name: Test
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: fe_clone
          POSTGRES_DB: fe_clone_test
    container:
      image: ruby:3.1.2
      env:
        RAILS_ENV: test

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: bundle-${{ hashFiles('**/Gemfile.lock') }}
      - name: Bundler and gem install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --path vendor/bundle

      - name: Copy database config
        run: cp config/database.yml.ci config/database.yml

      - name: Set up database
        run: |
          bundle exec rails db:create
      - name: run rspec
        run: bundle exec rspec
